### ISSUE TITLE
multipin branch

### ISSUE THREAD

**Issue by kersten** [Yona-Appletree/LEDscape#39]
Hey, was there a reason why you deleted the multipin branch? I would love to see it coming back, because I was using it. I killed my bbb and now i am stuck with setting up my old software :(

**Comment by Yona-Appletree** [comment]
Pardon my memory, but what was on the multipin branch? I don't have a log of it on my local copy, and I don't recall it.

**Comment by Yona-Appletree** [comment]
I'm closing this issue since I don't think it's a bug.
