### ISSUE TITLE
Development of new template

### ISSUE THREAD

**Issue by funkwizard** [Yona-Appletree/LEDscape#41]
Hi Yona,

Firstly, thank you for all your contributions to this branch of LEDScape.

I am not sure how to make direct contact with you, so I hope this message is not out of place. I'm wondering whether you would be available for some freelance development work.  I am looking for a pru template solution for another LED RGB driver chip.  The protocol is a slight modification to the WS281x template.  I would be happy for you to commit this solution to this branch once done.

Thanks

**Comment by Yona-Appletree** [comment]
I would be happy to talk about the parameters of this work with you. Please send an e-mail to lightatplay at gmail dot com. We, along with RGB123 ( Ryan O Hara) do both custom hardware and software relating to LEDscape. I look forward to working with you. I'll close this slip now.
